WebAppProwin/Areas/Admin/Controllers/HinhAnhController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppProwin.Areas.Admin.Models;

namespace WebAppProwin.Areas.Admin.Controllers
{
    public class HinhAnhController : Controller
    {
        // GET: Admin/HinhAnh
        ProwinShopEntities db = new ProwinShopEntities();
        public ActionResult Index()
        {
            AlbumModel model = new AlbumModel();
            return View(model.GetListAlbum());
        }

        public ActionResult GetListIMG(int id)
        {
            AlbumModel model = new AlbumModel();
            return View(model.GetListHinhAnh(id));
        }

        [HttpPost]
        public ActionResult CreateNewAlbum(string name)
        {
            AlbumModel model = new AlbumModel();

            if (model.NewAlbum(name))
            {
                string path = "~/Upload/" + name;
                try
                {
                    Directory.CreateDirectory(Server.MapPath(path));
                }catch
                {
                    return Json("Xay ra loi tao thu muc o server");
                }
                return RedirectToAction("Index");
            }
            else return Json("Xay ra loi");
        }
    }
}

WebAppProwin/Areas/Admin/Views/HinhAnh/GetListIMG.cshtml
@{
    ViewBag.Title = "GetListIMG";
    ViewBag.ID = "Hình Ảnh";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using WebAppProwin
@model List<HinhAnh>
    @Html.ActionLink("Trở về","Index","HinhAnh")
    @if (Model.Count > 0)
    {
        foreach(var item in Model)
        {
            <div>
                <img width="200px;" src="~/Upload/@item.path"/>
            </div>
        }
    }

WebAppProwin/Areas/Admin/Views/HinhAnh/Index.cshtml
@{
    ViewBag.Title = "HÌNH ẢNH";
    ViewBag.ID = "Hình Ảnh";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>

@using WebAppProwin.Areas.Admin.Models
@model List<AlbumModel>

<div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#uploadModel">
        TẢI-ẢNH-LÊN
    </button>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
        TẠO-ALBUM-MỚI
    </button>
</div>
<div>
    @if (Model.Count > 0)
    {
        foreach (var item in Model)
        {
            @Html.ActionLink(@item.TenAlbum, "GetListIMG", new { id = item.MaAlbum })
        }

    }

</div>

<!-- new album -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tên Album</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="HinhAnh/CreateNewAlbum" method="post">
                    <input type="text" name="name" placeholder="Nhập tên album" required />
                    <input type="submit" value="TẠO" />
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

<!-- Upload -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="~/Content/Admin/style.css" rel="stylesheet" />
<link rel="stylesheet" href="https://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="~/Content/Admin/jquery.fileupload.css">
<link rel="stylesheet" href="~/Content/Admin/jquery.fileupload-ui.css">
<noscript>
    <link rel="stylesheet" href="~/Content/Admin/jquery.fileupload-noscript.css">
</noscript>
<noscript>
    <link rel="stylesheet" href="~/Content/Admin/jquery.fileupload-ui-noscript.css">
</noscript>
<style>
    #fileupload {
        width: 100% !important;
    }

    .container {
        width: 100%;
    }

    #uploadModel {
        width: 100% !important;
        height:auto !important;
    }
        #uploadModel .modal-dialog{
            height:auto !important;
            width: 100% !important;
        }
            #uploadModel .modal-dialog .modal-content {
                height: auto !important;
                width: 55em !important;
            }
                #uploadModel .modal-dialog .modal-content .modal-body{
                    width:auto !important;
                }
</style>
<div class="modal" id="uploadModel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Upload</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <form id="fileupload" action="@Url.Action("/UploadFile/Index")" method="POST" enctype="multipart/form-data">
                        <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
                        <select name="TenAlbum">
                            @foreach (var item in Model)
                            {
                                <option value="@item.MaAlbum">@item.TenAlbum</option>
                            }
                        </select>
                        <div class="row fileupload-buttonbar">
                            <div class="col-lg-7">
                                <span class="btn btn-success fileinput-button">
                                    <i class="glyphicon glyphicon-plus"></i>
                                    <span>Add files...</span>
                                    <input type="file" name="files" multiple>
                                </span>
                                <button type="submit" class="btn btn-primary start">
                                    <i class="glyphicon glyphicon-upload"></i>
                                    <span>Start upload</span>
                                </button>
                                <button type="reset" class="btn btn-warning cancel">
                                    <i class="glyphicon glyphicon-ban-circle"></i>
                                    <span>Cancel upload</span>
                                </button>
                                <span class="fileupload-process"></span>
                            </div>
                            <div class="col-lg-5 fileupload-progress fade">
                                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                                </div>
                                <div class="progress-extended">&nbsp;</div>
                            </div>
                        </div>
                        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
            <button class="btn btn-primary start" disabled>
                <i class="glyphicon glyphicon-upload"></i>
                <span>Start</span>
            </button>
            {% } %}
            {% if (!i) { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
            <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
            <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}" {% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" crossorigin="anonymous"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="~/Scripts/Admin/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="https://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="https://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- blueimp Gallery script -->
<script src="https://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="~/Scripts/Admin/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="~/Scripts/Admin/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="~/Scripts/Admin/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="~/Scripts/Admin/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script src="~/Scripts/Admin/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script src="~/Scripts/Admin/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script src="~/Scripts/Admin/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="~/Scripts/Admin/jquery.fileupload-ui.js"></script>
<!-- The main application script -->
<script src="~/Scripts/Admin/main.js"></script>