WebAppProwin/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppProwin.Areas.Admin.Models;

namespace WebAppProwin.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: Admin/SanPham
        ProwinShopEntities db = new ProwinShopEntities();
        static int? temp_id_SanPham = 1;
        public ActionResult Index()
        {
            List<SanPham> m = db.SanPhams.ToList();
            return View(m);
        }
        public ActionResult ThemSanPham()
        {
            ViewSanPham m = new ViewSanPham();
            return View(m);
        }

        [HttpPost]
        public ActionResult ThemSanPham(SanPhamModel m)
        {
            m.Add(m);
            ViewSanPham view = new ViewSanPham();
            view.Message = "Thêm Sản Phẩm Thành Công.";
            return View(view);
        }

        public ActionResult ChiTietSP(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            temp_id_SanPham = id;
            ViewChiTiet view = new ViewChiTiet();

            List<MauSac> listMau = db.MauSacs.Where(x => x.MaSP == id).ToList();

            view.mausac = listMau;
            view.kichthuoc = db.KichThuocs.ToList();
            return View(view);
        }


        [HttpPost]
        public ActionResult ThemMau(MauModel model, HttpPostedFileBase[] img)
        {
            model.TenFile = img[0].FileName;
            model.Add(temp_id_SanPham, model);
            return RedirectToAction("ChiTietSP/"+temp_id_SanPham);
        }
    }
}

WebAppProwin/Areas/Admin/Views/SanPham/ChiTietSP.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/css/bootstrap-select.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/js/bootstrap-select.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "ChiTietSP";
    ViewBag.ID = "Danh Sách";
}
@using WebAppProwin.Areas.Admin.Models
@model ViewChiTiet
    <h1>Thêm mẫu</h1>
<div>
    <div>
        @using (Html.BeginForm("ThemMau", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div>
                <input type="text" placeholder="Ten Mau" name="TenMau" />
            </div>
            <div>
                <label>Image</label>
                <input type="file" multiple="multiple" value="Tải ảnh lên" name="img" />
            </div>
            <div>
                <input type="number" placeholder="So luong" name="Soluong" min="0" />
            </div>
            <div>
                <label>Size</label>
                <select class="selectpicker" multiple data-live-search="true" name="kich_thuoc">
                    @foreach (var item in Model.kichthuoc)
                    {
                        <option value="@item.MaKT">@item.Size</option>
                    }
                </select>
            </div>
            <div>
                <input type="text" name="Soluong" placeholder="Số lượng từng size"/>
            </div>
            <div>
                <button type="submit" name="submit" class="glyphicon glyphicon-ok btn btn-primary"> THÊM</button>
            </div>
        }

    </div>

    <script>
        $('select').selectpicker();
    </script>
</div>
<hr/>
@if (Model.mausac.Count() < 0)
{
    <p>Không có dữ liệu</p>
}
else
{
    <table>
        <thead>
            <tr>
                <th>
                    MaMau
                </th>
                <th>
                    TenMau
                </th>
                <th>
                    SoLuong
                </th>
                <th>
                    Kich thuoc
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.mausac)
            {
                <tr>
                    <td>@item.MaMau</td>
                    <td>@item.TenMau</td>
                    <td>@item.SoLuong</td>
                    <td>
                        @foreach (var i in item.MaMau_MaKT)
                        {
                            <p class="row">
                                @i.KichThuoc.Size
                                @*|
                                    @i.SoLuong*@
                            </p>

                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

WebAppProwin/Areas/Admin/Views/SanPham/Index.cshtml
@model IEnumerable<WebAppProwin.SanPham>

@{
    ViewBag.Title = "SẢN PHẨM";
    ViewBag.ID = "Kho Sản Phẩm";

    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @Html.ActionLink("THÊM SẢN PHẨM", "ThemSanPham")

        <table>
            <thead>
                <tr>
                    <th>
                        MaSP
                    </th>
                    <th>
                        MaTH
                    </th>
                    <th>
                        TenSP
                    </th>
                    <th>
                        Gia
                    </th>
                    <th>
                        Ngay nhap
                    </th>
                    <th>
                        Chi tiết
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaSP</td>
                        <td>@item.MaTH</td>
                        <td>@item.TenSP</td>
                        <td>@item.GiaSP</td>
                        <td>@item.NgayTao.Value.ToShortDateString()</td>
                        <td>
                            @Html.ActionLink("Xem", "ChiTietSP", new { id = item.MaSP })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

WebAppProwin/Areas/Admin/Views/SanPham/ThemSanPham.cshtml
@{
    ViewBag.Title = "THÊM SẢN PHẨM";
    ViewBag.ID = "Thêm sản phẩm";

    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using WebAppProwin.Areas.Admin.Models
@model ViewSanPham
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ThemSanPham</title>
</head>
<body>
    <div>
        <form action="ThemSanPham" method="post">
            <div class="row">
                <input type="text" name="TenSP" placeholder="Tên Sản Phẩm" />
            </div>
            <div>
                <label>Nhóm Sản Phẩm</label>
                <select name="MaTH">
                    @foreach (var item in Model.NhomSP)
                    {
                        <option value="@item.MaTH">@item.TenThuongHieu</option>
                    }
                </select>
                </div>
            <div>
                <label>Album</label>
                <select name="MaAlbum">
                    @foreach (var item in Model.albums)
                    {
                        <option value="@item.MaAlbum">@item.TenAlbum</option>
                    }
                </select>
                </div>
            <div>   
                <label>Danh Muc</label>
                <select name="MaDMC">
                    @foreach (var item in Model.DMCons)
                    {
                        <option value="@item.MaDMC">@item.TenDM</option>
                    }
                </select>
            </div>
            <div>
                <input type="number" name="GiaSP" placeholder="Đơn Giá" min="0"/>
            </div>
            <div>
                <textarea type="text" name="Mota" placeholder="Mô Tả"></textarea>
            </div>
            <div>
                <input type="text" name="Sale" placeholder="Sale" />
            </div>
            <div>
                <textarea name="NoiDung" placeholder="Nội dung"></textarea>
            </div> 
            <input type="submit" value="Hoàn Thành" />
        </form>
    </div>
</body>
</html>